# DO NOT MOVE THIS FILE
services:
  keycloak:
    container_name: lwdieb-keycloak
    image: keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./production/keycloak/realm/:/opt/keycloak/data/import/
    env_file: ./production/keycloak/.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8081:8080"
    cap_drop: [ALL]
    networks:
      - dashboard-network

  caddy:
    image: caddy:2
    container_name: lwdieb-caddy
    #restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./development/caddy/data:/data
      - ./development/caddy/config:/config
      - ./development/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge